(()=>{"use strict";
const $=id=>document.getElementById(id),DB_NAME="DentalFlowV1DB",STORE="patients";let db=null,patients=[],activePatientId=null,toastTimer;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const dateLabel=v=>{if(!v)return"—";try{return new Intl.DateTimeFormat("en-IN",{day:"numeric",month:"short",year:"numeric"}).format(new Date(v))}catch{return"—"}};
function toast(msg){const el=$("toast");el.textContent=msg;el.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove("show"),2600)}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE)){const s=d.createObjectStore(STORE,{keyPath:"id"});s.createIndex("updatedAt","updatedAt")}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||Error("Database open failed"));r.onblocked=()=>reject(Error("Database blocked by another tab"))})}
function txDone(tx){return new Promise((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error||Error("Storage transaction failed"));tx.onabort=()=>reject(tx.error||Error("Storage transaction aborted"))})}
async function getAll(){const tx=db.transaction(STORE,"readonly"),r=tx.objectStore(STORE).getAll();const list=await new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error||Error("Could not read records"))});await txDone(tx);return list.sort((a,b)=>(b.updatedAt||"").localeCompare(a.updatedAt||""))}
async function putPatient(p){const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(p);await txDone(tx)}
async function deletePatient(id){const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).delete(id);await txDone(tx)}
function closeMenu(){$("drawer").classList.remove("open");$("shade").classList.remove("show")}
function setView(v){["home","patients","backup"].forEach(x=>$("view-"+x).classList.toggle("hidden",x!==v));document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===v));closeMenu();if(v==="patients")setTimeout(()=>$("searchInput").focus({preventScroll:true}),80);if(v==="backup")updateStorageStatus();window.scrollTo({top:0,behavior:"smooth"})}
function emptyState(title,detail,button,id){return`<div class="empty"><strong>${esc(title)}</strong>${esc(detail)}${button?`<br><br><button id="${id}" class="primary">${esc(button)}</button>`:""}</div>`}
function patientCard(p){const initials=(p.name||"?").trim().split(/\s+/).slice(0,2).map(x=>x[0]||"").join("").toUpperCase(),meta=[p.phone||"No phone",p.age!==""&&p.age!=null?`${p.age} years`:"",p.gender||""].filter(Boolean).join(" · ");return`<button class="patient-card" data-open-patient="${esc(p.id)}"><span class="avatar">${esc(initials||"?")}</span><span class="patient-info"><strong>${esc(p.name)}</strong><small>${esc(meta)}</small></span><span class="chevron">›</span></button>`}
function render(){const today=new Date().toISOString().slice(0,10);$("totalPatients").textContent=patients.length;$("todayPatients").textContent=patients.filter(p=>(p.createdAt||"").slice(0,10)===today).length;const recent=patients.slice(0,4);$("recentPatients").innerHTML=recent.length?recent.map(patientCard).join(""):emptyState("No patients yet","প্রথম patient record তৈরি করে শুরু করো।","＋ Add first patient","emptyAddBtn");const q=($("searchInput").value||"").trim().toLowerCase(),filtered=patients.filter(p=>`${p.name||""} ${p.phone||""}`.toLowerCase().includes(q));$("patientCount").textContent=`${filtered.length} patient${filtered.length===1?"":"s"}`;$("patientsList").innerHTML=filtered.length?filtered.map(patientCard).join(""):emptyState(q?"No matching patients":"No patients yet",q?"অন্য নাম বা phone দিয়ে খুঁজে দেখো।":"নতুন patient যোগ করলে এখানে দেখা যাবে।",q?"Clear search":"＋ Add patient",q?"clearEmptySearch":"emptyAddBtn2");const a=$("emptyAddBtn");if(a)a.onclick=()=>openPatientForm();const b=$("emptyAddBtn2");if(b)b.onclick=()=>openPatientForm();const c=$("clearEmptySearch");if(c)c.onclick=()=>{$("searchInput").value="";render()}}
function openPatientForm(p=null){$("patientForm").reset();$("formError").textContent="";$("patientId").value=p?.id||"";$("dialogTitle").textContent=p?"Edit patient":"Add patient";$("patientName").value=p?.name||"";$("patientPhone").value=p?.phone||"";$("patientAge").value=p?.age??"";$("patientGender").value=p?.gender||"";$("patientNotes").value=p?.notes||"";$("patientDialog").showModal();setTimeout(()=>$("patientName").focus(),80)}
async function savePatient(e){e.preventDefault();$("formError").textContent="";const name=$("patientName").value.trim();if(!name){$("formError").textContent="Patient name is required.";return}const old=patients.find(p=>p.id===$("patientId").value),ageRaw=$("patientAge").value.trim(),now=new Date().toISOString(),id=old?.id||(crypto.randomUUID?crypto.randomUUID():"p-"+Date.now()+"-"+Math.random().toString(36).slice(2));const p={id,name,phone:$("patientPhone").value.trim(),age:ageRaw===""?"":Number(ageRaw),gender:$("patientGender").value,notes:$("patientNotes").value.trim(),createdAt:old?.createdAt||now,updatedAt:now};try{await putPatient(p);patients=await getAll();$("patientDialog").close();render();toast(old?"Patient updated":"Patient saved")}catch(err){$("formError").textContent="Save করা যায়নি। Browser storage পরীক্ষা করো।";console.error(err)}}
function showDetails(id){const p=patients.find(x=>x.id===id);if(!p)return;activePatientId=id;$("detailName").textContent=p.name;const fields=[["Phone",p.phone],["Age",p.age!==""&&p.age!=null?`${p.age} years`:""],["Gender",p.gender],["General notes",p.notes],["Created",dateLabel(p.createdAt)],["Last updated",dateLabel(p.updatedAt)]];$("detailBody").innerHTML=fields.map(([k,v])=>`<div class="detail-field"><small>${esc(k)}</small><div>${esc(v||"—")}</div></div>`).join("");$("detailDialog").showModal()}
async function removeActivePatient(){const p=patients.find(x=>x.id===activePatientId);if(!p)return;if(!confirm(`Delete patient "${p.name}"? This cannot be undone unless you have a backup.`))return;try{await deletePatient(p.id);patients=await getAll();$("detailDialog").close();render();toast("Patient deleted")}catch(err){toast("Delete failed. Please try again.");console.error(err)}}
function downloadJSON(name,data){const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportBackup(){downloadJSON(`dentalflow-backup-${new Date().toISOString().slice(0,10)}.json`,{app:"DentalFlow",formatVersion:1,exportedAt:new Date().toISOString(),patients});toast("Backup download started")}
async function restoreBackup(file){if(!file)return;try{const data=JSON.parse(await file.text());if(data.app!=="DentalFlow"||data.formatVersion!==1||!Array.isArray(data.patients))throw Error("Unsupported DentalFlow V1 backup");if(!data.patients.every(p=>p&&typeof p.name==="string"&&typeof p.id==="string"))throw Error("Invalid patient records in backup");if(!confirm(`Restore ${data.patients.length} patient records? This will replace all current patient records.`))return;const tx=db.transaction(STORE,"readwrite"),s=tx.objectStore(STORE);s.clear();data.patients.forEach(p=>s.put({...p,updatedAt:p.updatedAt||new Date().toISOString()}));await txDone(tx);patients=await getAll();render();toast("Backup restored successfully")}catch(err){alert("Restore failed: "+(err.message||"Invalid backup file"));console.error(err)}finally{$("restoreInput").value=""}}
function updateStorageStatus(){$("storageStatus").textContent=`Local database available · ${patients.length} patient records · approx. ${(new Blob([JSON.stringify(patients)]).size/1024).toFixed(1)} KB of record data`}
function bind(){ $("menuBtn").onclick=()=>$("drawer").classList.add("open")||$("shade").classList.add("show");$("closeMenu").onclick=closeMenu;$("shade").onclick=closeMenu;document.querySelectorAll("[data-view]").forEach(b=>b.addEventListener("click",()=>setView(b.dataset.view)));$("addTopBtn").onclick=()=>openPatientForm();$("addPatientBtn").onclick=()=>openPatientForm();$("homeAddBtn").onclick=()=>openPatientForm();$("homeFindBtn").onclick=()=>setView("patients");$("homeBackupBtn").onclick=()=>setView("backup");$("searchInput").oninput=render;$("clearSearch").onclick=()=>{$("searchInput").value="";render();$("searchInput").focus()};$("patientForm").addEventListener("submit",savePatient);$("dialogClose").onclick=()=>$("patientDialog").close();$("cancelForm").onclick=()=>$("patientDialog").close();$("detailClose").onclick=()=>$("detailDialog").close();$("detailDone").onclick=()=>$("detailDialog").close();$("editPatientBtn").onclick=()=>{const p=patients.find(x=>x.id===activePatientId);$("detailDialog").close();if(p)openPatientForm(p)};$("deletePatientBtn").onclick=removeActivePatient;$("exportBtn").onclick=exportBackup;$("restoreInput").onchange=e=>restoreBackup(e.target.files?.[0]);$("refreshStatus").onclick=updateStorageStatus;document.addEventListener("click",e=>{const card=e.target.closest("[data-open-patient]");if(card)showDetails(card.dataset.openPatient)});window.addEventListener("pageshow",()=>{if(db)refresh().catch(console.error)})}
async function refresh(){patients=await getAll();render();if(!$("view-backup").classList.contains("hidden"))updateStorageStatus()}
async function start(){bind();try{if(!("indexedDB"in window))throw Error("This browser does not support local database storage.");db=await openDB();await refresh()}catch(err){console.error(err);$("app").innerHTML=`<section class="panel"><div class="panel-copy"><h2>Storage could not start</h2><p>${esc(err.message||"Open this app in a modern browser and try again.")}</p><button class="secondary" onclick="location.reload()">Reload app</button></div></section>`}if("serviceWorker"in navigator&&(location.protocol==="https:"||location.hostname==="localhost"))navigator.serviceWorker.register("./sw.js").catch(console.warn)}
start()})();