(()=>{"use strict";
const $=id=>document.getElementById(id),DB_NAME="DentalFlowV1DB",PATIENTS="patients",VISITS="visits",TRANSACTIONS="transactions";
let db=null,patients=[],visits=[],transactions=[],activePatientId=null,activeVisitId=null,activeTransactionId=null,toastTimer;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const todayISO=()=>new Date().toISOString().slice(0,10);
const dateLabel=v=>{if(!v)return"—";try{return new Intl.DateTimeFormat("en-IN",{day:"numeric",month:"short",year:"numeric"}).format(new Date(v+"T00:00:00"))}catch{return v}};
const money=v=>{try{return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(Number(v)||0)}catch{return "₹"+(Number(v)||0).toFixed(2)}};
const makeId=prefix=>crypto.randomUUID?crypto.randomUUID():prefix+"-"+Date.now()+"-"+Math.random().toString(36).slice(2);
function toast(msg){const el=$("toast");el.textContent=msg;el.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove("show"),2600)}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,3);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(PATIENTS)){const s=d.createObjectStore(PATIENTS,{keyPath:"id"});s.createIndex("updatedAt","updatedAt")}if(!d.objectStoreNames.contains(VISITS)){const s=d.createObjectStore(VISITS,{keyPath:"id"});s.createIndex("patientId","patientId");s.createIndex("visitDate","visitDate")}if(!d.objectStoreNames.contains(TRANSACTIONS)){const s=d.createObjectStore(TRANSACTIONS,{keyPath:"id"});s.createIndex("date","date");s.createIndex("patientId","patientId")}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||Error("Database open failed"));r.onblocked=()=>reject(Error("Close other DentalFlow tabs and reload"))})}
function txDone(tx){return new Promise((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error||Error("Storage transaction failed"));tx.onabort=()=>reject(tx.error||Error("Storage transaction aborted"))})}
async function readStore(name){const tx=db.transaction(name,"readonly"),r=tx.objectStore(name).getAll();const list=await new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error||Error("Could not read records"))});await txDone(tx);return list}
async function getPatients(){return(await readStore(PATIENTS)).sort((a,b)=>(b.updatedAt||"").localeCompare(a.updatedAt||""))}
async function getVisits(){return(await readStore(VISITS)).sort((a,b)=>(b.visitDate||"").localeCompare(a.visitDate||""))}
async function getTransactions(){return(await readStore(TRANSACTIONS)).sort((a,b)=>(b.date||"").localeCompare(a.date||"")||(b.createdAt||"").localeCompare(a.createdAt||""))}
async function putRecord(storeName,record){const tx=db.transaction(storeName,"readwrite");tx.objectStore(storeName).put(record);await txDone(tx)}
async function deleteRecord(storeName,id){const tx=db.transaction(storeName,"readwrite");tx.objectStore(storeName).delete(id);await txDone(tx)}
function closeMenu(){$("drawer").classList.remove("open");$("shade").classList.remove("show")}
function setView(v){["home","patients","finance","backup"].forEach(x=>$("view-"+x).classList.toggle("hidden",x!==v));document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===v));closeMenu();if(v==="patients")setTimeout(()=>$("searchInput").focus({preventScroll:true}),80);if(v==="finance")renderFinance();if(v==="backup")updateStorageStatus();window.scrollTo({top:0,behavior:"smooth"})}
function emptyState(title,detail,button,id){return`<div class="empty"><strong>${esc(title)}</strong>${esc(detail)}${button?`<br><br><button id="${id}" class="primary">${esc(button)}</button>`:""}</div>`}
function patientCard(p){const initials=(p.name||"?").trim().split(/\s+/).slice(0,2).map(x=>x[0]||"").join("").toUpperCase(),meta=[p.phone||"No phone",p.age!==""&&p.age!=null?`${p.age} years`:"",p.gender||""].filter(Boolean).join(" · ");return`<button class="patient-card" data-open-patient="${esc(p.id)}"><span class="avatar">${esc(initials||"?")}</span><span class="patient-info"><strong>${esc(p.name)}</strong><small>${esc(meta)}</small></span><span class="chevron">›</span></button>`}
function render(){const today=todayISO();$("totalPatients").textContent=patients.length;$("todayPatients").textContent=patients.filter(p=>(p.createdAt||"").slice(0,10)===today).length;const recent=patients.slice(0,4);$("recentPatients").innerHTML=recent.length?recent.map(patientCard).join(""):emptyState("No patients yet","প্রথম patient record তৈরি করে শুরু করো।","＋ Add first patient","emptyAddBtn");const q=($("searchInput").value||"").trim().toLowerCase(),filtered=patients.filter(p=>`${p.name||""} ${p.phone||""}`.toLowerCase().includes(q));$("patientCount").textContent=`${filtered.length} patient${filtered.length===1?"":"s"}`;$("patientsList").innerHTML=filtered.length?filtered.map(patientCard).join(""):emptyState(q?"No matching patients":"No patients yet",q?"অন্য নাম বা phone দিয়ে খুঁজে দেখো।":"নতুন patient যোগ করলে এখানে দেখা যাবে।",q?"Clear search":"＋ Add patient",q?"clearEmptySearch":"emptyAddBtn2");const a=$("emptyAddBtn");if(a)a.onclick=()=>openPatientForm();const b=$("emptyAddBtn2");if(b)b.onclick=()=>openPatientForm();const c=$("clearEmptySearch");if(c)c.onclick=()=>{$("searchInput").value="";render()}}
function currentMonth(){return todayISO().slice(0,7)}
function renderFinance(){const month=currentMonth(),monthRows=transactions.filter(t=>(t.date||"").slice(0,7)===month),income=monthRows.filter(t=>t.type==="income").reduce((n,t)=>n+Number(t.amount||0),0),expense=monthRows.filter(t=>t.type==="expense").reduce((n,t)=>n+Number(t.amount||0),0);$("financeMonth").textContent=new Intl.DateTimeFormat("en-IN",{month:"long",year:"numeric"}).format(new Date(month+"-01T00:00:00"));$("monthIncome").textContent=money(income);$("monthExpense").textContent=money(expense);$("monthNet").textContent=money(income-expense);const recent=transactions.slice(0,50);$("transactionsList").innerHTML=recent.length?recent.map(t=>{const p=patients.find(x=>x.id===t.patientId);return`<article class="transaction-card"><div class="transaction-main"><span class="transaction-symbol ${t.type==="income"?"is-income":"is-expense"}">${t.type==="income"?"＋":"−"}</span><div class="transaction-info"><strong>${esc(t.category|| (t.type==="income"?"Collection":"Expense"))}</strong><small>${esc(dateLabel(t.date))}${p?" · "+esc(p.name):""}${t.method?" · "+esc(t.method):""}</small>${t.note?`<small class="transaction-note">${esc(t.note)}</small>`:""}</div><div class="transaction-side"><strong class="${t.type==="income"?"is-income-text":"is-expense-text"}">${t.type==="income"?"+":"−"}${esc(money(t.amount))}</strong><div class="transaction-actions"><button class="mini-btn" data-edit-transaction="${esc(t.id)}">Edit</button><button class="mini-btn" data-delete-transaction="${esc(t.id)}">Delete</button></div></div></div></article>`}).join(""):emptyState("No transactions yet","Collection বা clinic expense যোগ করলে এখানে দেখা যাবে।","＋ Add first entry","emptyTransactionBtn");const empty=$("emptyTransactionBtn");if(empty)empty.onclick=()=>openTransactionForm();}
function openTransactionForm(t=null,type=null){activeTransactionId=t?.id||null;$("transactionForm").reset();$("transactionFormError").textContent="";$("transactionId").value=t?.id||"";$("transactionDialogTitle").textContent=t?"Edit transaction":"Add transaction";$("transactionType").value=t?.type||type||"income";$("transactionDate").value=t?.date||todayISO();$("transactionAmount").value=t?.amount??"";$("transactionCategory").value=t?.category||(type==="expense"?"Other expense":"Treatment collection");$("transactionMethod").value=t?.method||"Cash";$("transactionNote").value=t?.note||"";const patientSelect=$("transactionPatient");patientSelect.innerHTML='<option value="">Not linked to a patient</option>'+patients.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}${p.phone?" · "+esc(p.phone):""}</option>`).join("");patientSelect.value=t?.patientId||"";$("transactionDialog").showModal();setTimeout(()=>$("transactionAmount").focus({preventScroll:true}),80)}
async function saveTransaction(e){e.preventDefault();$("transactionFormError").textContent="";const amount=Number($("transactionAmount").value);if(!Number.isFinite(amount)||amount<=0){$("transactionFormError").textContent="Amount zero-এর বেশি হতে হবে।";return}const old=transactions.find(t=>t.id===$("transactionId").value),now=new Date().toISOString(),patientId=$("transactionPatient").value;const t={id:old?.id||makeId("tx"),type:$("transactionType").value,date:$("transactionDate").value,amount:Math.round(amount*100)/100,category:$("transactionCategory").value,patientId,method:$("transactionMethod").value,note:$("transactionNote").value.trim(),createdAt:old?.createdAt||now,updatedAt:now};try{await putRecord(TRANSACTIONS,t);transactions=await getTransactions();$("transactionDialog").close();renderFinance();if(!$ ("view-backup").classList.contains("hidden"))updateStorageStatus();toast(old?"Transaction updated":"Transaction saved")}catch(err){$("transactionFormError").textContent="Entry save করা যায়নি। আবার চেষ্টা করো।";console.error(err)}}
async function deleteTransaction(id){const t=transactions.find(x=>x.id===id);if(!t)return;if(!confirm("এই financial entry delete করবে? Backup ছাড়া এটি ফিরিয়ে আনা যাবে না।"))return;try{await deleteRecord(TRANSACTIONS,id);transactions=await getTransactions();renderFinance();toast("Entry deleted")}catch(err){toast("Delete failed");console.error(err)}}
function openPatientForm(p=null){$("patientForm").reset();$("formError").textContent="";$("patientId").value=p?.id||"";$("dialogTitle").textContent=p?"Edit patient":"Add patient";$("patientName").value=p?.name||"";$("patientPhone").value=p?.phone||"";$("patientAge").value=p?.age??"";$("patientGender").value=p?.gender||"";$("patientNotes").value=p?.notes||"";$("patientDialog").showModal();setTimeout(()=>$("patientName").focus(),80)}
async function savePatient(e){e.preventDefault();$("formError").textContent="";const name=$("patientName").value.trim();if(!name){$("formError").textContent="Patient name is required.";return}const old=patients.find(p=>p.id===$("patientId").value),ageRaw=$("patientAge").value.trim(),now=new Date().toISOString(),id=old?.id||(crypto.randomUUID?crypto.randomUUID():"p-"+Date.now()+"-"+Math.random().toString(36).slice(2));const p={id,name,phone:$("patientPhone").value.trim(),age:ageRaw===""?"":Number(ageRaw),gender:$("patientGender").value,notes:$("patientNotes").value.trim(),createdAt:old?.createdAt||now,updatedAt:now};try{await putRecord(PATIENTS,p);patients=await getPatients();$("patientDialog").close();render();toast(old?"Patient updated":"Patient saved")}catch(err){$("formError").textContent="Save করা যায়নি। Browser storage পরীক্ষা করো।";console.error(err)}}
function showDetails(id){const p=patients.find(x=>x.id===id);if(!p)return;activePatientId=id;$("detailName").textContent=p.name;const fields=[["Phone",p.phone],["Age",p.age!==""&&p.age!=null?`${p.age} years`:""],["Gender",p.gender],["General notes",p.notes],["Created",dateLabel((p.createdAt||"").slice(0,10))],["Last updated",dateLabel((p.updatedAt||"").slice(0,10))]];$("detailBody").innerHTML=fields.map(([k,v])=>`<div class="detail-field"><small>${esc(k)}</small><div>${esc(v||"—")}</div></div>`).join("");renderVisitHistory();$("detailDialog").showModal()}
function patientVisits(){return visits.filter(v=>v.patientId===activePatientId).sort((a,b)=>(b.visitDate||"").localeCompare(a.visitDate||""))}
function renderVisitHistory(){const list=patientVisits();$("visitHistory").innerHTML=list.length?list.map(v=>{const detail=v.diagnosis||v.treatment||v.complaint||"Visit record";return`<article class="visit-card"><div class="visit-card-top"><strong>${esc(dateLabel(v.visitDate))}</strong><div class="visit-card-actions"><button class="mini-btn" data-edit-visit="${esc(v.id)}">Edit</button><button class="mini-btn" data-delete-visit="${esc(v.id)}">Delete</button></div></div><div class="visit-summary">${esc(detail)}${v.nextDate?`\nNext visit: ${esc(dateLabel(v.nextDate))}`:""}${v.followup?`\nFollow-up: ${esc(v.followup)}`:""}</div></article>`}).join(""):`<div class="visit-empty">এখনও কোনো clinical visit যোগ করা হয়নি।</div>`}
function openVisitForm(v=null){if(!activePatientId)return;if($("detailDialog").open)$("detailDialog").close();$("visitForm").reset();$("visitFormError").textContent="";$("visitId").value=v?.id||"";$("visitDialogTitle").textContent=v?"Edit clinical visit":"Add clinical visit";$("visitDate").value=v?.visitDate||todayISO();$("visitComplaint").value=v?.complaint||"";$("visitHistoryText").value=v?.history||"";$("visitExamination").value=v?.examination||"";$("visitDiagnosis").value=v?.diagnosis||"";$("visitTreatment").value=v?.treatment||"";$("visitAdvice").value=v?.advice||"";$("visitPrescription").value=v?.prescription||"";$("visitNextDate").value=v?.nextDate||"";$("visitFollowup").value=v?.followup||"";$("visitDialog").showModal()}
function closeVisitForm(){if($("visitDialog").open)$("visitDialog").close();if(activePatientId&&patients.some(p=>p.id===activePatientId))showDetails(activePatientId)}
async function saveVisit(e){e.preventDefault();$("visitFormError").textContent="";if(!activePatientId){$("visitFormError").textContent="Patient not selected.";return}const old=visits.find(v=>v.id===$("visitId").value),now=new Date().toISOString();const v={id:old?.id||(crypto.randomUUID?crypto.randomUUID():"v-"+Date.now()+"-"+Math.random().toString(36).slice(2)),patientId:activePatientId,visitDate:$("visitDate").value,complaint:$("visitComplaint").value.trim(),history:$("visitHistoryText").value.trim(),examination:$("visitExamination").value.trim(),diagnosis:$("visitDiagnosis").value.trim(),treatment:$("visitTreatment").value.trim(),advice:$("visitAdvice").value.trim(),prescription:$("visitPrescription").value.trim(),nextDate:$("visitNextDate").value,followup:$("visitFollowup").value,createdAt:old?.createdAt||now,updatedAt:now};try{await putRecord(VISITS,v);visits=await getVisits();$("visitDialog").close();showDetails(activePatientId);toast(old?"Visit updated":"Visit saved")}catch(err){$("visitFormError").textContent="Visit save করা যায়নি। আবার চেষ্টা করো।";console.error(err)}}
async function deleteVisit(id){const v=visits.find(x=>x.id===id);if(!v)return;if(!confirm("এই clinical visit record delete করবে?"))return;try{await deleteRecord(VISITS,id);visits=await getVisits();renderVisitHistory();toast("Visit deleted")}catch(err){toast("Visit delete failed");console.error(err)}}
async function removeActivePatient(){const p=patients.find(x=>x.id===activePatientId);if(!p)return;if(!confirm(`Delete patient "${p.name}" and all linked clinical visits? This cannot be undone unless you have a backup.`))return;try{const linked=visits.filter(v=>v.patientId===p.id),linkedTransactions=transactions.filter(t=>t.patientId===p.id);const tx=db.transaction([PATIENTS,VISITS,TRANSACTIONS],"readwrite");tx.objectStore(PATIENTS).delete(p.id);linked.forEach(v=>tx.objectStore(VISITS).delete(v.id));linkedTransactions.forEach(t=>tx.objectStore(TRANSACTIONS).put({...t,patientId:"",updatedAt:new Date().toISOString()}));await txDone(tx);patients=await getPatients();visits=await getVisits();transactions=await getTransactions();$("detailDialog").close();render();toast("Patient and linked visits deleted")}catch(err){toast("Delete failed. Please try again.");console.error(err)}}
function downloadJSON(name,data){const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportBackup(){downloadJSON(`dentalflow-backup-${todayISO()}.json`,{app:"DentalFlow",formatVersion:3,exportedAt:new Date().toISOString(),patients,visits,transactions});toast("Backup download started")}
async function restoreBackup(file){if(!file)return;try{const data=JSON.parse(await file.text());if(data.app!=="DentalFlow"||![1,2,3].includes(data.formatVersion)||!Array.isArray(data.patients))throw Error("Unsupported DentalFlow backup");const importedVisits=Array.isArray(data.visits)?data.visits:[],importedTransactions=Array.isArray(data.transactions)?data.transactions:[];if(!data.patients.every(p=>p&&typeof p.name==="string"&&typeof p.id==="string"))throw Error("Invalid patient records");if(!importedVisits.every(v=>v&&typeof v.id==="string"&&typeof v.patientId==="string"))throw Error("Invalid visit records");const patientIds=new Set(data.patients.map(p=>p.id));if(importedVisits.some(v=>!patientIds.has(v.patientId)))throw Error("Backup has a visit without a matching patient");if(!importedTransactions.every(t=>t&&typeof t.id==="string"&&["income","expense"].includes(t.type)&&Number.isFinite(Number(t.amount))&&Number(t.amount)>0&&typeof t.date==="string"))throw Error("Invalid financial transaction records");if(importedTransactions.some(t=>t.patientId&&!patientIds.has(t.patientId)))throw Error("Backup has a transaction without a matching patient");if(!confirm(`Restore ${data.patients.length} patients, ${importedVisits.length} visits and ${importedTransactions.length} transactions? This replaces all current records.`))return;const tx=db.transaction([PATIENTS,VISITS,TRANSACTIONS],"readwrite"),ps=tx.objectStore(PATIENTS),vs=tx.objectStore(VISITS),ts=tx.objectStore(TRANSACTIONS);ps.clear();vs.clear();ts.clear();data.patients.forEach(p=>ps.put(p));importedVisits.forEach(v=>vs.put(v));importedTransactions.forEach(t=>ts.put(t));await txDone(tx);patients=await getPatients();visits=await getVisits();transactions=await getTransactions();render();renderFinance();toast("Backup restored successfully")}catch(err){alert("Restore failed: "+(err.message||"Invalid backup file"));console.error(err)}finally{$("restoreInput").value=""}}
function updateStorageStatus(){$("storageStatus").textContent=`Local database available · ${patients.length} patients · ${visits.length} visits · ${transactions.length} transactions · approx. ${(new Blob([JSON.stringify({patients,visits,transactions})]).size/1024).toFixed(1)} KB`}
function bind(){$("menuBtn").onclick=()=>{$("drawer").classList.add("open");$("shade").classList.add("show")};$("closeMenu").onclick=closeMenu;$("shade").onclick=closeMenu;document.querySelectorAll("[data-view]").forEach(b=>b.addEventListener("click",()=>setView(b.dataset.view)));$("addTopBtn").onclick=()=>openPatientForm();$("addPatientBtn").onclick=()=>openPatientForm();$("homeAddBtn").onclick=()=>openPatientForm();$("homeFindBtn").onclick=()=>setView("patients");$("homeBackupBtn").onclick=()=>setView("backup");$("searchInput").oninput=render;$("clearSearch").onclick=()=>{$("searchInput").value="";render();$("searchInput").focus()};$("patientForm").addEventListener("submit",savePatient);$("dialogClose").onclick=()=>$("patientDialog").close();$("cancelForm").onclick=()=>$("patientDialog").close();$("detailClose").onclick=()=>$("detailDialog").close();$("detailDone").onclick=()=>$("detailDialog").close();$("editPatientBtn").onclick=()=>{const p=patients.find(x=>x.id===activePatientId);$("detailDialog").close();if(p)openPatientForm(p)};$("deletePatientBtn").onclick=removeActivePatient;$("addVisitBtn").onclick=()=>openVisitForm();$("visitClose").onclick=closeVisitForm;$("visitCancel").onclick=closeVisitForm;$("visitDialog").addEventListener("cancel",e=>{e.preventDefault();closeVisitForm()});$("visitForm").addEventListener("submit",saveVisit);$("visitHistory").addEventListener("click",e=>{const edit=e.target.closest("[data-edit-visit]"),del=e.target.closest("[data-delete-visit]");if(edit){const v=visits.find(x=>x.id===edit.dataset.editVisit);if(v)openVisitForm(v)}if(del)deleteVisit(del.dataset.deleteVisit)});$("addTransactionBtn").onclick=()=>openTransactionForm();$("quickCollectionBtn").onclick=()=>openTransactionForm(null,"income");$("quickExpenseBtn").onclick=()=>openTransactionForm(null,"expense");$("transactionClose").onclick=()=>$("transactionDialog").close();$("transactionCancel").onclick=()=>$("transactionDialog").close();$("transactionForm").addEventListener("submit",saveTransaction);$("transactionsList").addEventListener("click",e=>{const edit=e.target.closest("[data-edit-transaction]"),del=e.target.closest("[data-delete-transaction]");if(edit){const t=transactions.find(x=>x.id===edit.dataset.editTransaction);if(t)openTransactionForm(t)}if(del)deleteTransaction(del.dataset.deleteTransaction)});$("exportBtn").onclick=exportBackup;$("restoreInput").onchange=e=>restoreBackup(e.target.files?.[0]);$("refreshStatus").onclick=updateStorageStatus;document.addEventListener("click",e=>{const card=e.target.closest("[data-open-patient]");if(card)showDetails(card.dataset.openPatient)});window.addEventListener("pageshow",()=>{if(db)refresh().catch(console.error)})}
async function refresh(){patients=await getPatients();visits=await getVisits();transactions=await getTransactions();render();renderFinance();if(!$("view-backup").classList.contains("hidden"))updateStorageStatus();if(activePatientId&&$("detailDialog").open)renderVisitHistory()}
async function start(){bind();try{if(!("indexedDB"in window))throw Error("This browser does not support local database storage.");db=await openDB();await refresh()}catch(err){console.error(err);$("app").innerHTML=`<section class="panel"><div class="panel-copy"><h2>Storage could not start</h2><p>${esc(err.message||"Open this app in a modern browser and try again.")}</p><button class="secondary" onclick="location.reload()">Reload app</button></div></section>`}if("serviceWorker"in navigator&&(location.protocol==="https:"||location.hostname==="localhost"))navigator.serviceWorker.register("./sw.js").catch(console.warn)}
start()})();